Repository 10up/theme-scaffold, pull requests merged in 2018-10, with the labels that each got.

#66 Replace LiveReload with Browsersync
  README.md
  gulp-tasks/cssnano.js
  gulp-tasks/webpack.js
  gulpfile.babel.js
  package.json
Labels: enhancement

#77 Add async/defer tags for enqueueing scripts
  includes/core.php
Labels: enhancement, question

#86 Update Node engine to greater than or equal to 8.11
  package.json
Labels: bug
