Repository 10up/theme-scaffold, pull requests merged in 2019-04, with the labels that each got.

#114 Adding new core template function
  header.php
  includes/core.php
Labels: Enhancement

#111 Switch to Webpack
  README.md
  config/webpack.common.js
  config/webpack.dev.js
  config/webpack.prod.js
  config/webpack.settings.js
  gulp-tasks/css.js
  gulp-tasks/cssclean.js
  gulp-tasks/cssnano.js
  gulp-tasks/lint-css.js
  gulp-tasks/setenv.js
  gulp-tasks/webpack.js
  gulpfile.babel.js
  includes/core.php
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.babel.js
Labels: under review

#132 Add WP Acceptance support and initial tests
  README.md
  composer.json
  composer.lock
  tests/wpa/FrontendTest.php
  tests/wpa/StandardTest.php
  wpacceptance.json
Labels: Enhancement

#134 Updated BrowserSync to fix npm vulnerabilities.
  package-lock.json
  package.json
Labels: add to plugin repo
